use std::env;
use std::fs;
use std::path::Path;

// 「粉丝福利」MiniMax key 的滚动 XOR 混淆垫片。
// 注意: 客户端混淆只能延缓提取、不能真正保护密钥 —— 真正的止损是给该 key 设额度封顶。
const GIFT_PAD: [u8; 8] = [0x9E, 0x37, 0x79, 0xB1, 0x5A, 0xC4, 0x2D, 0xE6];

fn main() {
    // tauri_build 仅在桌面构建时调用; server (Docker) 构建无需 Tauri 上下文/资源清单,
    // 跳过它即可在无 webkit2gtk 的 Linux 镜像里编译同一份源码。
    #[cfg(feature = "desktop")]
    tauri_build::build();

    // 构建期从环境变量注入礼物 key(CI 走 GitHub secret POLARIS_GIFT_MINIMAX_KEY)。
    // 本地 dev 构建未设此变量时, 注入空串 → 运行时不种子, 不影响开发。
    println!("cargo:rerun-if-env-changed=POLARIS_GIFT_MINIMAX_KEY");
    let key = env::var("POLARIS_GIFT_MINIMAX_KEY").unwrap_or_default();

    let obf: Vec<String> = key
        .as_bytes()
        .iter()
        .enumerate()
        .map(|(i, b)| format!("0x{:02X}", b ^ GIFT_PAD[i % GIFT_PAD.len()]))
        .collect();
    let pad: Vec<String> = GIFT_PAD.iter().map(|b| format!("0x{:02X}", b)).collect();

    let body = format!(
        "// AUTO-GENERATED by build.rs — 构建期注入, 勿手改。\n\
         pub(crate) const GIFT_MINIMAX_OBF: &[u8] = &[{}];\n\
         pub(crate) const GIFT_MINIMAX_PAD: &[u8] = &[{}];\n",
        obf.join(", "),
        pad.join(", "),
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    fs::write(Path::new(&out_dir).join("gift_key.rs"), body).expect("write gift_key.rs failed");
}
